### ISSUE TITLE
In total setup 4 computers with development software by Saturday January 16th

### ISSUE THREAD

**Issue by politerock** [353pobots/2016-Stronghold#2]

**Comment by politerock** [comment]
Cloning is now underway.

**Comment by politerock** [comment]
Cloning is completed. 

### Once activation of LabVEIW is completed this issue can be closed.

**Comment by rpickus** [comment]
Activation of LabVIEW has been completed on the 2 machines where it was not active

**Comment by Rich353** [comment]
Vision libraries are missing from these computers.
Please install.

**Comment by colbyk123** [comment]
This can be closed
@Rich353 we will make a new issue with your comment
