### ISSUE TITLE
Build test chassis with encoders and gyroscope

### ISSUE THREAD

**Issue by politerock** [353pobots/2016-Stronghold#3]

**Comment by Rich353** [comment]
Update this issue:

Mate Prototyping board to Rebound Rumble.
With Camera, Gyro

Get it working.

Then add Encoders to the wheels

**Comment by Rich353** [comment]
The board is on the Rebound Rumble.
It is driving with the 2015 LabView.

The camera and Gryo are wired.

Next step:
1) Test Gyro with sample code
2) Test camera with sample code
3) Test with 2016 LabVIEW

**Comment by politerock** [comment]
I'm putting this under a new issue (#8) and closing this out since the original problem has been resolved.
