### ISSUE TITLE
Tower - Build Tower

### ISSUE THREAD

**Issue by Rich353** [353pobots/2016-Stronghold#4]
Phase 1: build enough for high scoring goals w /vision tracking tape
Phase 2: add low scoring goals
Phase 3: add ground level elements
Phase 4: add pull up bar

**Comment by Rich353** [comment]
Please share this with Mr. Smith

**Comment by Rich353** [comment]
What is the status of this issue?

For now, we only need Phase 1.
What is the ETA or estimated time of completion of phase 1?

**Comment by colbyk123** [comment]
Phase 1 almost done, the goals are built the vision tape just needs to be added
@Rich353

**Comment by Rich353** [comment]
Good.

--Rich
