### ISSUE TITLE
Programming Laptop - Investigate connection loss

### ISSUE THREAD

**Issue by Rich353** [353pobots/2016-Stronghold#5]
Concerned the programming laptop has an issues causing connection loss with the robots.
The symptoms are the driver station software losses connection to the robot intermitenly.

My current esitmate of the cause is the wireless card on the laptop has a problem or the power management feature are causing the wireless card to pause or reset.

Test by connection with wired ethernet cable
Test by changing power management features off or never power off the card
Test with desktop programming computer via DLink/bridge

**Comment by colbyk123** [comment]
@macinfous (Alex) and I have concluded that it is the internal wifi card in the laptop, we swapped the routers on the robot its self, and use the new KOP router with the laptop and had no packet loss when we   swapped it back to the internal card we had more packet loss than time connected 
@Rich353 
**I think we can close this issue**
:+1:

**Comment by politerock** [comment]
@colbyk123 Agreed.
