### ISSUE TITLE
2016 Software requirements review

### ISSUE THREAD

**Issue by Rich353** [353pobots/2016-Stronghold#6]
Investigate software version requirements for the RoboRIO.
Collect version and update if required on the desktop programming computer.

Printout instructions for updating the RoboRio.

Review with Mr. Shapp when ready.

**Comment by politerock** [comment]
# Instructions for updating the roboRIO:

http://www.ni.com/white-paper/52593/en/

Second Link:
http://wpilib.screenstepslive.com/s/4485/m/13503/l/273817-updating-your-roborio-firmware

# Instructions for updating LabVIEW:

http://www.ni.com/download/first-robotics-software-2015/5773/en/
http://wpilib.screenstepslive.com/s/4485/m/13503/l/144150-installing-the-frc-2016-update-suite-all-languages

**Comment by wacko1212** [comment]
Firmware downloaded onto laptop, did not have time to upload to robot. Will be uploaded by Wednesday the 20th 
@Rich353 @colbyk123 @macinfous

**Comment by Rich353** [comment]
Thanks for these links, It was helpful for me.

**Comment by colbyk123** [comment]
where are we on this right now?

**Comment by rpickus** [comment]
The RoboRio firmware and the OS were both updated.  We were also able to get the camera working.  At this point, however, the NI Vision module still has broken links, so a "default" project will still not build cleanly.

**Comment by colbyk123** [comment]
@rpickus What do you mean by "OS" and would you like us to try and work on the NI vision

**Comment by rpickus** [comment]
After we updated the firmware, we had to "image" the RoboRio (all part of the instructions that were printed out for us).  
Yes, please work on the NI Vision issue.  Thanks

**Comment by colbyk123** [comment]
This can be closed
