### ISSUE TITLE
Repair or replace Wi-Fi card and swap hard drive

### ISSUE THREAD

**Issue by colbyk123** [353pobots/2016-Stronghold#7]
**We have concluded that it is the internal card**
#5

We need to swap the hard drive that is in laptop right now, but **before** we do that we need to check if it is with in the year of the dell coverage

**Comment by politerock** [comment]
@colbyk123 The easiest way to solve this issue would be to use a USB Wi-Fi adapter.

**Comment by colbyk123** [comment]
@macinfous but it if it under warranty and we could get it fixed why wouldn't we?

**Comment by politerock** [comment]
@colbyk123 It would be the easiest solution if we don't have a warranty. I should have clarified this in my earlier statement.

**Comment by Rich353** [comment]
Who is determining the state of the warranty?

**Comment by colbyk123** [comment]
@Rich353 how would we do this.....Acer with the service tag?

**Comment by politerock** [comment]
The warranty is void
