### ISSUE TITLE
Test Rebound Rumble's Camera and Gyroscope with LabVIEW 2016

### ISSUE THREAD

**Issue by politerock** [353pobots/2016-Stronghold#8]
### Next step:

1) Test Gyro with sample code
2) Test camera with sample code
3) Test with 2016 LabVIEW

**Comment by colbyk123** [comment]
How would we see the camera feed?
We need to find a second joy stick for operations

**Comment by Rich353** [comment]
The Gyro should be wired to an Analog input.
I think it is currently wired to a Digital port. (DIO)
